project:
  type: website
  output-dir: docs

website:
  title: "my_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jobinjosemecheril
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css



